---
abstract: 'Create word bags from text, and operate over them.'
author:
  - 'Andre Santos <andrefs@cpan.org>'
build_requires:
  Module::Build: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Perfide-WordBags
provides:
  Text::Perfide::WordBags:
    file: lib/Text/Perfide/WordBags.pm
    version: 0.01_01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_01
